# Generated by Django 5.0.2 on 2024-04-15 08:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_cat_querry_cat_remove_querry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querry',
            name='query_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.querry')),
            ],
        ),
    ]
