# Generated by Django 5.0.2 on 2024-04-18 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_querry_query_id_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Home.querry'),
        ),
    ]
