# Generated by Django 5.0.3 on 2024-04-22 08:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_alter_answers_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.answers')),
            ],
        ),
    ]
