# Generated by Django 5.0.4 on 2024-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='ratings',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
