# Generated by Django 5.0.4 on 2024-04-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_answers_ratings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
