# Generated by Django 5.0.4 on 2024-04-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='ratings',
            field=models.FloatField(default=0.0),
        ),
    ]
