# Generated by Django 5.0.4 on 2024-04-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_answers_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='ratings',
            new_name='rating',
        ),
    ]
