# Generated by Django 5.1.1 on 2024-09-29 16:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_rename_ratings_answers_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.FloatField()),
                ('user_rater', models.EmailField(max_length=254)),
                ('date', models.DateField(default=datetime.date.today)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Home.answers')),
                ('user_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to='Home.signup')),
            ],
        ),
    ]
